spring.application.name=omniops-backend

spring.datasource.url=jdbc:mysql://localhost:3306/omniops
spring.datasource.username=root
spring.datasource.password=Root@12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
jwt.secret=OmniOpsSuperSecretKeyForJwtAuthentication2026OmniOpsSecureKey
jwt.expiration=86400000